// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzq24X1dqyMFBpq3djg4_yYIH3neC3a2s',
    appId: '1:224793841397:web:4cc2b44d0c246c09a1ffbc',
    messagingSenderId: '224793841397',
    projectId: 'genprd-9675b',
    authDomain: 'genprd-9675b.firebaseapp.com',
    storageBucket: 'genprd-9675b.firebasestorage.app',
    measurementId: 'G-BJE1PN3NQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rn5E1VYu5iQxjKuF_HLWKFkRZHgO0HE',
    appId: '1:224793841397:android:bfb71a69f76bc74aa1ffbc',
    messagingSenderId: '224793841397',
    projectId: 'genprd-9675b',
    storageBucket: 'genprd-9675b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLjSe1JGyc-PwRHtpu_X1Gwo17MYADfY',
    appId: '1:224793841397:ios:495f27f0daba5daea1ffbc',
    messagingSenderId: '224793841397',
    projectId: 'genprd-9675b',
    storageBucket: 'genprd-9675b.firebasestorage.app',
    iosBundleId: 'com.example.genprd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLjSe1JGyc-PwRHtpu_X1Gwo17MYADfY',
    appId: '1:224793841397:ios:495f27f0daba5daea1ffbc',
    messagingSenderId: '224793841397',
    projectId: 'genprd-9675b',
    storageBucket: 'genprd-9675b.firebasestorage.app',
    iosBundleId: 'com.example.genprd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzq24X1dqyMFBpq3djg4_yYIH3neC3a2s',
    appId: '1:224793841397:web:3158c66116e61f62a1ffbc',
    messagingSenderId: '224793841397',
    projectId: 'genprd-9675b',
    authDomain: 'genprd-9675b.firebaseapp.com',
    storageBucket: 'genprd-9675b.firebasestorage.app',
    measurementId: 'G-T53N1G5TLM',
  );
}
